In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = Variable(torch.tensor([2.]), requires_grad=True)
fx = x**4
d_f = fx.backward(gradient=torch.ones(1))
x.grad

tensor([32.])

In [3]:
x = torch.tensor([2.], requires_grad=True)
y = x**4
dy = y.backward()
x.grad

tensor([32.])

 <div class="math">
\begin{align}
y = x^4\\
\therefore dy = y.backward() = \frac{dy}{dx} = 4*x^3\\
\therefore x.grad = \frac{df}{dx}_{x=2} =4*2^3 = 32
\end{align}
</div>

In [4]:
x = Variable(torch.tensor([5.,4.]), requires_grad=True)
fx = (x**2).sum()
df = fx.backward()
x.grad

tensor([10.,  8.])

<div class = 'math'>
\begin{align*}
    &f\colon R^2 \longrightarrow R\\
    &\ni \forall  x = \left(x_{1},x_{2}\right) \in R^2\\
    &f(x) = x_{1}^2+x_{1}^2
\end{align*}
\begin{align*}
    \frac{df}{dx} = \left(\frac {df}{dx_1},\frac{df}{dx_2}\right)\\
    \because\frac{df}{dx_1} = 2*x_1 \\
    \frac{df}{dx_2} = 2*x_2\\
    \therefore \frac{df}{dx} = \left(2x_1,2x_2\right)\\
    \therefore \frac{df}{dx}_{x=\left(5,4\right)} = \left(2*5,2*4\right) = (10,8)
\end{align*}   
</div>

In [ ]:
x = Variable(torch.tensor(4.), requires_grad=True)
f = Variable(torch.ones(2,1), requires_grad=False)
f[0] = x**2
f[1] = x**3
df = f.backward(gradient=torch.ones(f.size()))
x.grad

<div class = 'math'>
\begin{align*}
    &f\colon R \longrightarrow R^2\\
    &\ni \forall  x \in R\\
    &f(x) = (x^2+x^3) = x^2i+x^3j
\end{align*}
\begin{align*}
    \frac{df}{dx} = 2xi+3x^2j\\
    \therefore \frac{df}{dx}_{x=4} = (2*4)i+(3*4^2)j = 8+48 = 56
\end{align*}   
</div>

In [ ]:
x = Variable(torch.tensor([2.,2.]), requires_grad=True)
f = Variable(torch.ones(3,1), requires_grad=False)
f[0] = x[0]**2
f[1] = x[1]**3
f[2] = x[1]**4
df = f.backward(gradient=torch.ones(f.size()))
x.grad

<div class = 'math'>
\begin{align*}
    &f\colon R^2 \longrightarrow R^3\\
    &\ni \forall  x = \left(x_{1},x_{2}\right) \in R^2\\
    &f(x) = \left(x_1^2,x_2^3,x_2^4\right)
\end{align*}
\begin{align*}
    \frac{df}{dx} = \left(\frac {df}{dx_1},\frac{df}{dx_2}\right)\\
    \because\frac{df}{dx_1} = 2x_1 \\
    \frac{df}{dx_2} = 3x_2^2+4x_2^3\\
    \therefore \frac{df}{dx} = \left(2x_1,3x_2^2+4x_2^3\right)\\
    \therefore \frac{df}{dx}_{x=(2,2)} = (2*2,3*2^2+4*2^3) = (4,44)
\end{align*}   
</div>